apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  releaseName: headlamp
  targetNamespace: headlamp-system
  install:
    createNamespace: true
  upgrade:
    force: true
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: "0.39.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  values: 
    ingress:
      enabled: true
      ingressClassName: traefik
      labels:
        app.kubernetes.io/part-of: traefik
      hosts:
        - host: headlamp.apps.home.arpa
          paths:
            - path: /
              type: ImplementationSpecific
    initContainers:
      - command:
          - /bin/sh
          - '-c'
          - >-
            mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown
            -R 100:101 /build
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        name: headlamp-plugins
        securityContext:
          privileged: false
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - emptyDir: {}
        name: headlamp-plugins 
