apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-install
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/metallb  
  prune: true
  wait: true 
  sourceRef:
    kind: GitRepository
    name: flux-system