apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h
  url: https://metallb.github.io/metallb
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: proxmox
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
  ref:
    semver: "0.5.5" 
  secretRef:
    name: ghcr-creds
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: proxmox
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/sergelogvinov/charts
  type: oci
  secretRef:
    name: ghcr-creds
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 1h
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    semver: "v1.7.1" 
  secretRef:
    name: dockerio-creds