apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy 
  namespace: flux-system
spec:
  releaseName: oauth2-proxy
  targetNamespace: oauth2-proxy-system
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
      version: "10.1.3"
