apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy 
  namespace: flux-system
spec:
  releaseName: oauth2-proxy
  targetNamespace: oauth2-proxy-system
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
      version: "10.1.3"
  values:
    # 1. Map the K8s Secret to Environment Variables
      extraEnv:
        - name: OKTA_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: okta-creds
              key: client-id
        - name: OKTA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: okta-creds
              key: client-secret
        - name: PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: okta-creds
              key: cookie-secret

      # 2. Reference them in the Config
      alphaConfig:
        enabled: true
        configFile: |-
          # Note the use of ${VAR_NAME} to pull the value
          cookie_secret: "${PROXY_COOKIE_SECRET}"

          injectRequestHeaders:
            - name: Authorization
              values:
                - claim: access_token
                  prefix: 'Bearer '

          providers:
            - id: okta
              provider: oidc
              # Use the environment variables here
              clientID: "${OKTA_CLIENT_ID}"
              clientSecret: "${OKTA_CLIENT_SECRET}"

              oidcConfig:
                issuerURL: "https://dev-msiuc0jdc2o4exg3.us.auth0.com/"
                emailClaim: email
                insecureAllowUnverifiedEmail: true
                audienceClaims:
                   - aud
              scope: "openid email profile"

          upstreamConfig:
            upstreams:
              - id: main
                path: /
                uri: "http://headlamp.headlamp-system.svc.cluster.local"
      config:
        cookieSecret: "${PROXY_COOKIE_SECRET}"
        emailDomains:
          - "*"
