apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
  # Ensure this is in the same namespace as your ExternalSecret 
  # or use a ClusterSecretStore if you want it available everywhere.
  namespace: external-secrets-system 
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token # The K8s secret containing your BW Token
            key: token
            namespace: external-secrets-system
      # FIX 1: Point to the correct namespace where your SDK pod is running
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets-system.svc.cluster.local:9998
      
      # FIX 2: Point to the Internal CA we just created
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoekNDQVN5Z0F3SUJBZ0lVS0VkMzdMNUM2WnZ3ZllzeHdZeUNBM0UyNUw0d0NnWUlLb1pJemowRUF3SXcKSVRFZk1CMEdBMVVFQXhNV2JtOXlkR2hqYkc5MVpDMXBiblJsY201aGJDMWpZVEFlRncweU5qQXpNREl3TWpFMApNekZhRncweU5qQTFNekV3TWpFME16RmFNQ0V4SHpBZEJnTlZCQU1URm01dmNuUm9ZMnh2ZFdRdGFXNTBaWEp1CllXd3RZMkV3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVIyejUxMmJNcEtMZUpBUFVQbEM0c3QKZW0ySnlocDZhUDVMeVgzS2FvTmg4MXpyalQ0MWFJaUdtOW1QaXh1S3BQZEZqV2xtd2h2NUJrM0F1QTdJUW1tQQpvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVCjVwWWtmSk9GWEhBN1Y4YXRyQURJdkNzL0VDb3dDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBTzJTTmNNRS84UUMKS1p0WDVzUW4xek92NmJDSTNKMXZwajlJY3FneTJUQ0dBaUVBeStsOTFhb3hpQ3pRdVhqa3FBanErRUpGbWxGaQpFR29lSGVjVm50TUNuMEk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0Ks 
      organizationID: 117c189e-93a7-4cf3-a8c8-b401002b74b3
      projectID: 4ba4e35f-05f7-495a-83d4-b4030023d054
