# clusters/test-cluster/infrastructure.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/test-cluster/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true 
