apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets 
  namespace: flux-system
spec:
  releaseName: external-secrets
  targetNamespace: external-secrets-system
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      version: "2.0.0"
  values:
    bitwarden-sdk-server:
      enabled: true
    controller:
      extraVolumes:
        - name: internal-ca
          secret:
            # Now looking in the same namespace as the controller
            secretName: northcloud-internal-ca-secret
            items:
              - key: tls.crt  # Use tls.crt as it's the full public cert
                path: tls-ca.crt

      extraVolumeMounts:
        - name: internal-ca
          mountPath: /etc/ssl/certs/northcloud-ca.crt
          subPath: tls-ca.crt
          readOnly: true

      env:
        - name: SSL_CERT_FILE
          value: /etc/ssl/certs/northcloud-ca.crt
