apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  releaseName: gateway-api
  targetNamespace: gateway-api-system
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: gateway-api
      sourceRef:
        kind: HelmRepository
        name: gateway-api
        namespace: flux-system
  values:
    # Install the Gateway API CRDs before installing the helm chart.
    # This is idempotent and will never remove existing CRDs.
    gatewayCRDInstaller:
      # Disable the installation of the Gateway API CRDs.
      enabled: true
      # Configure the image used to install the Gateway API CRDs.
      image:
        repository: "alpine/kubectl"
        tag: "1.33.3"
      # Version of the Gateway API CRDs to install.
      # Docs: https://gateway-api.sigs.k8s.io/installation/
      version: "0.2.0"
      # Whether to install experimental CRDs. May be either "standard" or "experimental".
      # Docs: https://gateway-api.sigs.k8s.io/concepts/versioning/
      channel: "standard"
      # Which CRDs to install.
      # Reference: https://github.com/kubernetes-sigs/gateway-api/tree/v1.2.0/config/crd/standard
      resources:
        - gateway.networking.k8s.io_gatewayclasses
        - gateway.networking.k8s.io_gateways
        - gateway.networking.k8s.io_httproutes
        - gateway.networking.k8s.io_referencegrants
        - gateway.networking.k8s.io_grpcroutes
        - gateway.networking.k8s.io_tlsroutes
