apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-cluster-issuer.yaml
  - bind9-cluster-issuer.yaml
  - local-ca-cluster-issuer.yaml
  - self-signed-bootstrap-cluster-issuer.yaml
  - northcloud-internal-ca.yaml