apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi
  namespace: flux-system
spec:
  releaseName: proxmox-csi
  targetNamespace: proxmox-csi-system
  interval: 30m
  chart:
    spec:
      chart: proxmox-csi-plugin
      version: "v1.19.2"
      sourceRef:
        kind: HelmRepository
        name: proxmox
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    existingConfigSecret: "proxmox-csi-config"
    existingConfigSecretKey: "config.yaml"
    config:
      clusters: []
    storageClass:
      - name: proxmox-local-lvm 
        storage: local-lvm       
        reclaimPolicy: Delete
        fstype: ext4
        cache: directsync        
        ssd: tru