apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: test-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: GHCR_TOKEN
    - secretKey: username
      remoteRef:
        key: GHCR_USERNAME
